name: Build Desktop App

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: linux
            build_cmd: npx electron-builder --linux AppImage deb rpm --publish never
          - os: windows-latest
            artifact_name: windows
            build_cmd: npx electron-builder --win --publish never
          - os: macos-latest
            artifact_name: macos
            build_cmd: npx electron-builder --mac --publish never

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build App Installers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ${{ matrix.build_cmd }}

      - name: Upload Installers
        uses: actions/upload-artifact@v4
        with:
          name: nodeloki-${{ matrix.artifact_name }}
          path: dist/